services:
    _defaults:
        public: false

    Runroom\TranslationBundle\Admin\TranslationAdmin:
        public: true
        arguments: [null, Runroom\TranslationBundle\Entity\Translation, null]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Translations' }

    Runroom\TranslationBundle\Service\TranslationService:
        arguments:
            $repository: '@Runroom\TranslationBundle\Repository\TranslationRepository'
            $translator: '@translator'

    Runroom\TranslationBundle\Repository\TranslationRepository:
        arguments:
            $registry: '@doctrine'
        tags: [doctrine.repository_service]

    Runroom\TranslationBundle\Twig\TranslationExtension:
        arguments:
            $service: '@Runroom\TranslationBundle\Service\TranslationService'
        tags: [twig.extension]
