services:
    _defaults:
        public: false

    Runroom\SortableBehaviorBundle\Controller\SortableAdminController:
        public: true
        arguments:
            $translator: '@translator'
            $accessor: '@property_accessor'
            $positionHandler: '@sortable_behavior.position'

    Runroom\SortableBehaviorBundle\Services\ORMPositionHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
        calls:
            - [setPositionField, ['%sortable.behavior.position.field%']]
            - [setSortableGroups, ['%sortable.behavior.sortable_groups%']]

    Runroom\SortableBehaviorBundle\Services\GedmoPositionHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $listener: !service
                class: Gedmo\Sortable\SortableListener
                calls: [[setAnnotationReader, ['@annotation_reader']]]

    Runroom\SortableBehaviorBundle\Twig\ObjectPositionExtension:
        arguments:
            $positionHandler: '@sortable_behavior.position'
        tags:
            - { name: twig.extension }

