services:
    _defaults:
        public: false

    Runroom\SortableBehaviorBundle\Controller\SortableAdminController:
        public: true
        arguments:
            $accessor: '@property_accessor'
            $positionHandler: '@sortable_behavior.position'

    Runroom\SortableBehaviorBundle\Service\ORMPositionHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $positionField: '%sortable.behavior.position.field%'
            $sortableGroups: '%sortable.behavior.sortable_groups%'
        calls: [[setPropertyAccessor, ['@property_accessor']]]

    Runroom\SortableBehaviorBundle\Service\GedmoPositionHandler:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $listener: !service
                class: Gedmo\Sortable\SortableListener
                calls: [[setAnnotationReader, ['@annotation_reader']]]
        calls: [[setPropertyAccessor, ['@property_accessor']]]

    Runroom\SortableBehaviorBundle\Twig\ObjectPositionExtension:
        arguments:
            $positionHandler: '@sortable_behavior.position'
        tags: [twig.extension]
