services:
    _defaults:
        public: false

    Runroom\RenderEventBundle\Controller\TemplateController:
        public: true
        arguments:
            $renderer: '@Runroom\RenderEventBundle\Renderer\PageRenderer'
        tags: [controller.service_arguments]

    Runroom\RenderEventBundle\Renderer\PageRenderer:
        arguments:
            $twig: '@twig'
            $eventDispatcher: '@event_dispatcher'
            $pageViewModel: '@runroom.render_event.page_view_model'

    runroom.render_event.page_view_model: ~

    twig.error_renderer.html:
        class: App\ErrorRenderer\TwigErrorRenderer
        decorates: error_renderer.html
        arguments:
            $twig: '@twig'
            $fallbackErrorRenderer: '@twig.error_renderer.html.inner'
            $debug: !service { factory: ['@App\ErrorRenderer\TwigErrorRenderer', isDebug], arguments: ['@request_stack', '%kernel.debug%']  }
            $renderer: '@Runroom\RenderEventBundle\Renderer\PageRenderer'
