services:
    runroom.basic_page.admin.basic_page:
        class: Runroom\BasicPageBundle\Admin\BasicPageAdmin
        public: true
        arguments: [~, Runroom\BasicPageBundle\Entity\BasicPage, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Basic pages' }
