services:
    _defaults:
        public: false

    Runroom\RedirectionBundle\Admin\RedirectAdmin:
        public: true
        arguments: [null, Runroom\RedirectionBundle\Entity\Redirect, null]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Redirects' }

    Runroom\RedirectionBundle\Listener\RedirectListener:
        arguments:
            $repository: '@Runroom\RedirectionBundle\Repository\RedirectRepository'
        tags: [kernel.event_subscriber]

    Runroom\RedirectionBundle\Listener\AutomaticRedirectSubscriber:
        arguments:
            $urlGenerator: '@router'
            $propertyAccessor: '@property_accessor'
            $configuration: []

    Runroom\RedirectionBundle\Repository\RedirectRepository:
        arguments:
            $registry: '@doctrine'
        tags: [doctrine.repository_service]
