services:
    _defaults:
        public: false

    Runroom\RedirectionBundle\Listener\RedirectListener:
        arguments:
            $repository: '@Runroom\RedirectionBundle\Repository\RedirectRepository'
        tags: [kernel.event_subscriber]

    Runroom\RedirectionBundle\Repository\RedirectRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
